### PR TITLE
Eda data visualizations

### PR DESCRIPTION
**Pull request by thejjserg**
I created multiple graphs to visualize different variables and their relationships with other variables. There are no interpretations yet as I just wanted to see the relationships prior to analysis.

I am fairly interested in the life expectancy variable, particularly when it comes to Zimbabwe. A correlation statistic will be needed if we want to see if GDP has anything to do with it, but in our first couple of graphs, it looks like this will require additional data or research.

### CODE REVIEW

**Comment by thejjserg** [comment]
Assigned Gustavo and Fernando to review the PR.

**Comment by GALLP900** [comment]
Here are my comments:
- The first countplot from what I can see it is counting how many data point are grouped per country. While the plot is nice, I feel the plot does not give more relevant information other than there are 16 datapoints, one for each year, maybe worth reviewing if we really need that plot
- The second plot is the same, we are counting how many datapoint are divided per year, however the key information is missing. we have 6 data points for each year, one for each country.  Maybe not not showing a plot for it?
- The histogram of life expectancy maybe worth showing 6 subplots in one figure given the large differences between life exp between countries. That is the main reason the histogram is hard to interpret also. Also applies to histograms of GDPs
- The boxplots are really nice. also shows very clear the life exp differences for each country
- The scatter plot for Life vs GDPs are key in this project. I also tried to plot all of the countries in one but the GDP diff makes it too hard. Maybe worth to make subplots too?

**Comment by thejjserg** [comment]
Agreed with your points, Gustavo. I'll look to make those suggestions.

**Comment by fer78** [comment]
This is my comment:

* The Bar Chart for Country and Year shows us that all countries have the same number of data recorded in the same years. This information is important to know the integrity of the data but can be shown with queries instead of graphics and included in the data validation part. 
* The boxplots and scatterplot of life expectancy by year show us a gradual growth of life expectancy for all countries in the dataset. 
* The histogram and boxplots of Life Expectancy, the histogram of GDP, show that there are significant differences between countries that suggest a grouping association to look for relationships between them. 
* The scatterplot that relates GDP and Life Expectancy is the most interesting one, suggesting three distinct groups of relationships between these variables. These findings can be the starting point for more detailed analysis by country or region.

**Comment by fer78** [comment]
Nice graphics, particularly the Scatterplot of Year vs GDP by Country. It's evident that Germany and the USA are responsible for the GDP downturn seen in 2008 on the group under study in the trend chart. Mexico also appears to have contributed, albeit with a minimal decrease. The United States and China were the only countries in the group that consistently increased their GDP after 2009. Germany had a slight and steady rise but did not recover after 2008; its GDP has been fluctuating without showing an upward trend. According to Wikipedia, the '2008 crisis' is also referred to as the global economic crisis, which originated in the United States. The crisis is attributed to several main factors, including regulatory failures, the overvaluation of financial products, a global food crisis, and the spike in oil prices due to the invasion of Iraq. However, life expectancy rates did not seem to be affected by this economic downturn.

**Comment by GALLP900** [comment]
@thejjserg I deleted one line that stated EDA-Data Visualization that was causing merge conflicts

**Comment by thejjserg** [comment]
Removing this branch

**Pull request closed without merging**
