### PR TITLE
Added two new variables, GDP Inc and Life Inc 

### LINKED ISSUE #9: Show realative GDP change vs relative Life Exp Change

### PR DESCRIPTION
**Pull request by GALLP900**
Using and plotting this variables allows us to see changes in GDP and Life Exp more clearly:

- Year 2000 is the baseline since the data is taken from that year onwards.
- This eliminates the GDP magnitude order difference between USA and Zimbabwe for example.

### CODE REVIEW

**Comment by thejjserg** [comment]
Reviewing the PR

**Comment by thejjserg** [comment]
The Multi-Variate barplots are very well done. I like that they're grouped by Country with the Year separated by a gradual color. I think the weakness for this graph is the differentiation between consecutive years. For example, it's difficult to find the difference between 2010 to 2011 as the colors are too similar to distinguish, but I think the point of the graph is to notice the gradual change of the X and Y variables hence the gradual change in color of the Z variable. However, I do think it's important to note that in this review.

Interesting points for research 
- Chile has a spike increase in GDP change, and it appears to be declining. 
- Mexico had a positive, decrease in GDP change, but has since recovered.

Suggested Changes:
1. Re-labeling United States of America to USA to shorten the label on the graph. This is just my personal aesthetic choice. The country name is significantly longer than the rest and it sticks out like a sore thumb.
2. Do the lambda functions be calculated using a base from the initial year or a change from the previous year? What are your thoughts there?

**Comment by fer78** [comment]
The graph shows the relative change over time within each country, providing a measure of GDP growth and life expectancy at birth, indicating a positive relationship between life expectancy and GDP. 

Interesting cases such as Zimbabwe, which have seen significant increases in life expectancy, emerge. External studies confirm that there is a bimodal distribution in the relationship between life expectancy (which was also seen in the life expectancy histogram graph made by other colleagues), suggesting that there are two distinct groups of countries according to their economic development and that in countries with lower economic development, variations in GDP have a considerable impact on life expectancy as it is more affected by literacy and nutrition. In countries with higher incomes, life expectancy is influenced by factors such as healthcare and pharmaceutical spending and lifestyles.

The relationship between life expectancy and GDP is very different in each country as there are many economic and political variables that interfere and are not the same in all countries. Studies assert that GDP is only related to Life Expectancy by 30%.

**Comment by GALLP900** [comment]
Thanks for the comments:
@thejjserg Yes I tested that too before. The relative change was used to see the tendency over the 15 years, that is compared to 2000 as a baseline. Measuring based on the previous year would be like measuring the absolute change of GDP and life which did not provide a reasonable explanation. In practical terms, a GDP inc and life inc based on a year-to-year basis didn't make any sense in the real world. For example, if the GPD decreased by 1 million USD and people lost half a year of their lives that same year? I think GDP inc and Life Inc need to be seen as a change over longer times, to see the trend sort of speak.  Year-to-year changes are on a second plane in this dataset I would say. It is more to see the overall benefit of economic growth, regardless of the country or GDP magnitude.  
@fer78 those are interesting comments, I suggest we use them in the conclusions or recommendations for sure. I think we need to be a bit cautious in the initial data analysis and not speculate too much on the causation, that is not focus yet on the reason behind the behavior of the data, instead only state what the actual data is showing. But the recommendations or further analysis should definitely include this.

**Comment by thejjserg** [comment]
Gustavo, agreed with your POV. I will be attempting to merge your branch now.

**Comment by calvinalee2006** [comment]
I viewed the project my personal opinion is that it is done very well!

**Pull request merged**
